fastq_input_dir = "/g/boulard/sformich/galaxy_transfer/H3K4me3_Ren_Snyder/input_data"

rule all:
  input:
    "/g/boulard/sformich/galaxy_transfer/H3K4me3_Ren_Snyder/input_data/Ren_ChIP_fastqc.html"   

rule fastqc_my_file:
  input:
    "{fastq_input_dir}/{fastqfile_name}.fastqsanger.gz"
  output:
    "{fastqfile_name}_fastqc.html"
    "{fastqfile_name}_fastqc.txt"
  shell:
    "fastqc {input}"
